### ISSUE TITLE
capstone kanban board setup

### ISSUE THREAD

**Issue by ZewdieMc** [ZewdieMc/BiteBuddy#21]
- The [link for the project](https://github.com/ZewdieMc/javascript-group-capstone/projects/1) is here.
- There are only two members in our team.

**Comment by BregornOriginal** [comment]
## Hi @TEAM 🥇 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations! 

## Highlights

✅ Good work on setup the kanban board 🥇 

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Comment by ZewdieMc** [comment]
@BregornOriginal, thank you we are grateful.
